language: cpp
compiler: gcc

install:
  - wget https://github.com/premake/premake-core/releases/download/v5.0.0-alpha13/premake-5.0.0-alpha13-linux.tar.gz -O premake.tar.gz
  - tar -xf premake.tar.gz
  - ./premake5 gmake
  - cd build/gmake

script:
  make
